apiVersion: v1
kind: Pod
metadata:
  name: emptyDir-demo
  labels:
    app.kubernetes.io/name: emptyDir
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name:  emptyDir-vol
        mountPath: /var/log/
  - name: alma
    image:  almalinux:9
    command: 
    - 'sleep'
    - '10000'
    volumeMounts:
      - name: emptyDir-vol
        mountPath: /mnt/log
  volumes:
    - name:  emptyDir-vol
      emptyDir: 
        sizeLimit: 500Mi