apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-04f35485b17534d8f
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-demo
  labels:
    purpose: testing
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: ebs-demo-vol
          mountPath: /usr/share/nginx
  volumes:
    - name: ebs-demo-vol
      persistentVolumeClaim:
        claimName: ebs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: ebs-service
spec:
  type: LoadBalancer
  selector:
    purpose: testing
  ports:
  - protocol: tcp
    port: 80
    targetPort: 80