apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: roboshop-efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1 
kind: Pod
metadata:
  name: roboshop-efs
  labels:
    purpose: testing
spec:
  containers:
    - name: nginx-efs
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: dynamic-efs-vol
          mountPath: /usr/share/nginx/html

  volumes:
    - name: dynamic-efs-vol
      persistentVolumeClaim:
        - claimName: roboshop-efs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
spec:
  type: LoadBalancer
  selector:
    purpose: testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80