apiVersion: v1
kind: Pod
metadata:
  name: alma-demo
  namespace: roboshop-dev
  labels:
    purpose: labels-test
spec:
  containers:
  - name: alma
    image: almalinux:10
    command: ['sleep','10000']