apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: roboshop-dev
  labels:
    name: roboshop-dev
    env: dev
    purpose: multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  - name: alma
    image: almalinux:10
    command: ['sleep','10000']