apiVersion: v1 
kind: Pod
metadata:
  name: labels-test
  labels:
    name: labels
    purpose: labels-test
    env: dev
    project: roboshop-dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80