apiVersion: v1 
kind: Pod
metadata:
  name: env-testing
  labels:
    name: roboshop 
    purpose: env-testing
    env: dev
    project: roboshop-dev
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: Name
      value: Anurag
    - name: purpose
      value: testing
    - name: env
      value: dev
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80